using UnityEngine;

namespace AnalogKeyboardMSC
{
    public static class Convert
    {
        //unity KeyCode to usb hid code
        public static ushort ConvertKeyCode(KeyCode id) => id switch
        {
            KeyCode.A => 4,
            KeyCode.B => 5,
            KeyCode.C => 6,
            KeyCode.D => 7,
            KeyCode.E => 8,
            KeyCode.F => 9,
            KeyCode.G => 10,
            KeyCode.H => 11,
            KeyCode.I => 12,
            KeyCode.J => 13,
            KeyCode.K => 14,
            KeyCode.L => 15,
            KeyCode.M => 16,
            KeyCode.N => 17,
            KeyCode.O => 18,
            KeyCode.P => 19,
            KeyCode.Q => 20,
            KeyCode.R => 21,
            KeyCode.S => 22,
            KeyCode.T => 23,
            KeyCode.U => 24,
            KeyCode.V => 25,
            KeyCode.W => 26,
            KeyCode.X => 27,
            KeyCode.Y => 28,
            KeyCode.Z => 29,
            KeyCode.Alpha1 => 30,
            KeyCode.Alpha2 => 31,
            KeyCode.Alpha3 => 32,
            KeyCode.Alpha4 => 33,
            KeyCode.Alpha5 => 34,
            KeyCode.Alpha6 => 35,
            KeyCode.Alpha7 => 36,
            KeyCode.Alpha8 => 37,
            KeyCode.Alpha9 => 38,
            KeyCode.Alpha0 => 39,
            KeyCode.Return => 40,
            KeyCode.Escape => 41,
            KeyCode.Backspace => 42,
            KeyCode.Tab => 43,
            KeyCode.Space => 44,
            KeyCode.Minus => 45,
            KeyCode.Equals => 46,
            KeyCode.LeftBracket => 47,
            KeyCode.RightBracket => 48,
            KeyCode.Backslash => 49,
            KeyCode.Semicolon => 51,
            KeyCode.Quote => 52,
            KeyCode.BackQuote => 53,
            KeyCode.Less => 54,
            KeyCode.Greater => 55,
            KeyCode.Question => 56,
            KeyCode.CapsLock => 57,
            KeyCode.F1 => 58,
            KeyCode.F2 => 59,
            KeyCode.F3 => 60,
            KeyCode.F4 => 61,
            KeyCode.F5 => 62,
            KeyCode.F6 => 63,
            KeyCode.F7 => 64,
            KeyCode.F8 => 65,
            KeyCode.F9 => 66,
            KeyCode.F10 => 67,
            KeyCode.F11 => 68,
            KeyCode.F12 => 69,
            KeyCode.Print => 70,
            KeyCode.ScrollLock => 71,
            KeyCode.Pause => 72,
            KeyCode.Insert => 73,
            KeyCode.Home => 74,
            KeyCode.PageUp => 75,
            KeyCode.Delete => 76,
            KeyCode.End => 77,
            KeyCode.PageDown => 78,
            KeyCode.RightArrow => 79,
            KeyCode.LeftArrow => 80,
            KeyCode.DownArrow => 81,
            KeyCode.UpArrow => 82,
            KeyCode.Numlock => 83,
            KeyCode.KeypadDivide => 84,
            KeyCode.KeypadMultiply => 85,
            KeyCode.KeypadMinus => 86,
            KeyCode.KeypadPlus => 87,
            KeyCode.KeypadEnter => 88,
            KeyCode.Keypad1 => 89,
            KeyCode.Keypad2 => 90,
            KeyCode.Keypad3 => 91,
            KeyCode.Keypad4 => 92,
            KeyCode.Keypad5 => 93,
            KeyCode.Keypad6 => 94,
            KeyCode.Keypad7 => 95,
            KeyCode.Keypad8 => 96,
            KeyCode.Keypad9 => 97,
            KeyCode.Keypad0 => 98,
            KeyCode.KeypadPeriod => 99,
            KeyCode.LeftControl => 224,
            KeyCode.LeftShift => 225,
            KeyCode.LeftAlt => 226,
            KeyCode.LeftWindows => 227,
            KeyCode.RightControl => 228,
            KeyCode.RightShift => 229,
            KeyCode.RightAlt => 230,
            KeyCode.RightWindows => 231,
            KeyCode.None => 0,
            _ => 0 // Default fallback for unknown IDs
        };
    }
}
